package com.showPricing;


public class MultiShowBooking {

	public static void main(String[] args) {
		double totalRevenue = 0.00;
		MultiShowPricing movieAvengers = new Movies("Avengers", "Movie", "Regular", 200, 3, 10, 10, true);
		totalRevenue += movieAvengers.calculateTotalCost();

		MultiShowPricing movieInception = new Movies("Inception", "Movie", "VIP", 500, 5, 10, 10, false);
		totalRevenue += movieInception.calculateTotalCost();
		
		MultiShowPricing concert = new Concert("Live Music Fest", "Concert", "Standard", 1000, 4, 5);
		totalRevenue += concert.calculateTotalCost();
		
		System.out.println("Total Revenue generated by all the shows: "+totalRevenue);
	}

}
